### ISSUE TITLE
Schema.org markup

### ISSUE THREAD

**Issue by jameslittle** [lloydmeta/metascraper#10]
Would be great if this could be extended to the supported Schema.org markup types: microdata, RDFa, JSON-LD. Examples here:
https://schema.org/Product

with the ability for the user to specify which markup types (and/or schemas) they are interested in, to help with performance.

**Comment by lloydmeta** [comment]
@jameslittle that sounds like a great idea :) When I wrote this, the use case was quite small + I hadn't heard of schema.org. I don't currently have the bandwidth to work on this though, so please feel free to send a PR.

**Comment by lloydmeta** [comment]
I just updated this lib to add support for custom Document data extractors via the `Schema` trait.

The `ScrapeUrl` message now has a `schemas` attribute that defaults to `Seq(OpenGraph, NormalPage)`, which prioritises `Schema`s that come first in the list.

Unfortunately, this still doesn't allow us to deal with any kind of data we want because `Schema` is still tied to Jsoup's Document type. This will have to improve to handle any kind of String I guess :)

**Comment by lloydmeta** [comment]
Never mind, with v0.2.8, you can now fully customise scraping by implementing `SchemaFactory` and `Schema`.

In essence, `SchemaFactory` is given a `Response` (from AsyncHttpClient), and needs to return a list of `Schema` which implement the scraping methods. 

Then, include your custom SchemaFactory in the ScrapeUrl message. Closing this for now, but if you have questions, please don't hesitate to ask or send PRs !
